version: "3.9"
services:
  mongo_node_1:
    container_name: mongo_node_1
    hostname: mongo_node_1
    image: "mongo"
    expose:
      - "27017"
    volumes:
      - /path/to/your/OS/folder/data/node_1:/data/db
      - /path/to/your/OS/folder/ssl/node_1:/data/ssl
      - /path/to/your/OS/folder/config:/data/config
    restart: always
    entrypoint: ["/usr/bin/mongod", "--config", "/data/config/cluster.conf"]
    networks:
      my_network:
        ipv4_address: 170.17.5.5
    extra_hosts:
      - "localhost:(YOUR MACHINE/SERVER IP)"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mdb_admin
      MONGO_INITDB_ROOT_PASSWORD: mdb_pass
  mongo_node_2:
    container_name: mongo_node_2
    hostname: mongo_node_2
    image: "mongo"
    expose:
      - "27017"
    volumes:
      - /path/to/your/OS/folder/data/node_2:/data/db
      - /path/to/your/OS/folder/ssl/node_2:/data/ssl
      - /path/to/your/OS/folder/config:/data/config
    restart: always
    entrypoint: ["/usr/bin/mongod", "--config", "/data/config/cluster.conf"]
    networks:
      my_network:
        ipv4_address: 170.17.5.6
    extra_hosts:
      - "localhost:(YOUR MACHINE/SERVER IP)"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mdb_admin
      MONGO_INITDB_ROOT_PASSWORD: mdb_pass
  mongo_node_arbiter:
    container_name: mongo_node_arbiter
    hostname: mongo_node_arbiter
    image: "mongo"
    expose:
      - "27017"
    volumes:
      - /path/to/your/OS/folder/data/node_arbiter:/data/db
      - /path/to/your/OS/folder/ssl/node_arbiter:/data/ssl
      - /path/to/your/OS/folder/config:/data/config
    restart: always
    entrypoint: ["/usr/bin/mongod", "--config", "/data/config/cluster.conf"]
    networks:
      my_network:
        ipv4_address: 170.17.5.7
    extra_hosts:
      - "localhost:(YOUR MACHINE/SERVER IP)"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mdb_admin
      MONGO_INITDB_ROOT_PASSWORD: mdb_pass
networks:
  my_network:
    name: my_network_default
    ipam: 
      driver: default
      config:
        - subnet: 170.17.0.0/16
          ip_range: 170.17.0.0/16
          gateway: 170.17.5.254